# Generated by Django 4.0.1 on 2022-03-27 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateAndLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='research/file/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='research/covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Concentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.DecimalField(decimal_places=15, max_digits=20)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.dateandlocation')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxTemp', models.DecimalField(decimal_places=3, max_digits=20)),
                ('minTemp', models.DecimalField(decimal_places=3, max_digits=20)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.dateandlocation')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.research')),
            ],
        ),
    ]
