# Generated by Django 4.0.3 on 2022-03-28 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatefactor',
            name='avgPrecipitation',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climatefactor',
            name='avgTemp',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climatefactor',
            name='avgWindSpeed',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climatefactor',
            name='research',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.research'),
        ),
    ]
