# Generated by Django 4.0.3 on 2022-03-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_climatefactor_avgprecipitation_climatefactor_avgtemp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateandlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='dateandlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20),
        ),
    ]
