# Generated by Django 4.0.3 on 2022-03-28 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_dateandlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatefactor',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.research'),
        ),
    ]
